apiVersion: v1
kind: Service
metadata:
  name: goodfood-delivery
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: goodfood-delivery