---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apitest
    spec:
      containers:
      - name: apitest
        image: beaurval/apitest:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: apitest
---
apiVersion: v1
kind: Service
metadata:
  name: apitest
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apitest